[DOJO-8] shadcn の初期化をする
Greek-Academy/alpha-dojo-v2 pull request #1
Opened 2024-11-10 03:35 UTC by iusok3386

@HonjyouDaisuke さんが First Commit b580d43bf4e39f555b723a21c56c794a61943933 でほとんどやってくださりました。
Git のユーザー名の変更を忘れていて、コミット者が u713551d になっておりますが、@iusok3386 です。
[Jira] TO DO: [DOJO-8](https://alpha-dojo.atlassian.net/browse/DOJO-8?atlOrigin=eyJpIjoiYjY5MTEzNDU4MzE5NDdmNmE4NDkxOTYzODExNmEzZWIiLCJwIjoiaiJ9)

2024-11-10 05:37 UTC, itakosu55 commented
Tailwind の色設定できてませんでした...
今からやります

2024-11-14 03:11 UTC, HonjyouDaisuke reviewed
遅くなって、申し訳ありません。色の設定ありがとうございます。
最初なので、できれば使い方サンプル的に、ボタンなどのコンポーネントで使用サンプルを書いてただけるとありがたいです。
設定内容はLGTMです。

2024-11-14 12:23 UTC, itakosu55 commented
ボタンの使用例は [dev/components/button](https://github.com/Greek-Academy/alpha-dojo-v2/tree/dev/components/button) ブランチで作りかけてます。
(ボタンコンポーネントを作成中です)
と思っていたのですが、[create-button-component](https://github.com/Greek-Academy/alpha-dojo-v2/tree/create-button-component) ブランチと競合してしまいそうですね...

2024-11-14 12:43 UTC, itakosu55 commented
ちなみに、今後レビュアーは @HonjyouDaisuke さんでよろしいでしょうか？

2024-11-16 23:10 UTC, itakosu55 commented
スクリーンショット (ボタン)
![image](https://github.com/user-attachments/assets/db581195-ae03-4916-87b3-16fd16909609)

2024-11-18 08:47 UTC, Harineko0 requested changes
LGTM！
一部コメント付けました

2024-11-18 08:47 UTC, Harineko0 commented on tailwind.config.ts
> +			base_p: {
完全リプレースなので、dojo v1 のプロパティは追加しなくて良いと思いますよー

2024-11-18 08:47 UTC, Harineko0 commented on tailwind.config.ts
> +		minWidth: {
同上

2024-11-20 00:55 UTC, itakosu55 commented on tailwind.config.ts
> +			base_p: {
修正しました！
https://github.com/Greek-Academy/alpha-dojo-v2/pull/1/commits/340b856e1592d2a8637525335b5b80a649be64c3

2024-11-20 00:55 UTC, iusok3386 commented on tailwind.config.ts
> +		minWidth: {
修正しました！
https://github.com/Greek-Academy/alpha-dojo-v2/pull/1/commits/340b856e1592d2a8637525335b5b80a649be64c3

2024-11-20 00:56 UTC, iusok3386 commented
dojo v1 由来の設定の削除と、
コンフリクトを解消しました

2024-11-20 08:57 UTC, Harineko0 approved these changes
LGTM！ありがとうございます

2024-11-20 11:17 UTC, merged