[DOJO-16] コンポーネントの作成 (Toggle Group)
Greek-Academy/alpha-dojo-v2 pull request #10
Opened 2024-11-30 14:35 UTC by iusok3386

shadcn の [Toggle Group](https://ui.shadcn.com/docs/components/toggle-group) の改造版です。

Variant に Outline を指定すると、Material Design 3 の [Filter Chip](https://m3.material.io/components/chips/specs#e900592f-75a4-4298-853c-bedd8f462f83) のようなデザインになります。

checkWithSelect 属性を true にすることで、選択時にチェックアイコンが表示されます。

tailwind.config.ts の色の指定方法にマズイ点があったので、それも修正しています。
参考: https://tailwindcss.com/docs/customizing-colors#using-css-variables

https://github.com/user-attachments/assets/e49cc085-3bb2-4d37-90c5-80c5c06dff7c

2024-11-30 15:40 UTC, iusok3386 commented
lint は 2 文字スペースの設定のようなので、
大量にスペースが消されてますね...(笑)

2024-12-06 01:40 UTC, Harineko0 requested changes

2024-12-06 01:40 UTC, Harineko0 commented on tailwind.config.ts
> +			},
on は primary, secondary の foreground と同じで OK です！

2024-12-06 01:40 UTC, Harineko0 commented on tailwind.config.ts
> +  			lg: 'var(--radius))',
このかっこはミスですかね？

2024-12-06 03:50 UTC, iusok3386 commented on tailwind.config.ts
> +			},
Container の on なので、コントラスト比が怪しそうですが…

2024-12-06 03:52 UTC, iusok3386 commented on tailwind.config.ts
> +  			lg: 'var(--radius))',
ほんとだ
修正しておきます！

2024-12-07 12:26 UTC, iusok3386 commented on tailwind.config.ts
> +			},
修正しました！
https://github.com/Greek-Academy/alpha-dojo-v2/commit/18f291540966d3257b1c84553020bd7cc0d7ec76

2024-12-07 12:27 UTC, iusok3386 commented on tailwind.config.ts
> +  			lg: 'var(--radius))',
修正しました！
https://github.com/Greek-Academy/alpha-dojo-v2/pull/10/commits/9162deb2285240e900109ff0e12c95d0db3c8342

2024-12-07 14:02 UTC, Harineko0 approved these changes
LGTM です！ありがとうございます(* ᴗ ᴗ)⁾⁾

2024-12-07 14:19 UTC, merged