primary-buttonを追加しました
Greek-Academy/alpha-dojo-v2 pull request #2
Opened 2024-11-13 14:22 UTC by kobayashi020

コンポーネント作成のテストとして、primary-buttonを追加しました

note:
・buttonの文字をtitleで受け取るようにしています
・onClickを受け取って機能を実装しています

2024-11-14 03:17 UTC, HonjyouDaisuke reviewed
レビューしました。
このボタンにアイコンをつけたいときは、`props`で`icon`を渡せば、`title`の前につけてくれるようにしたいです。できますでしょうか？

2024-11-14 03:17 UTC, HonjyouDaisuke commented on app/components/primary-button.tsx
> +        <Button variant="outline" onClick={props.onClick}>{props.title}</Button>
昨日言うのを忘れていましたが、`PrimaryButton`なので、`variant`は"outline"ではなく"primary"のほうがよさそうですね。
```
<Button variant="outline" onClick={props.onClick}>{props.title}</Button>
→<Button variant="primary" onClick={props.onClick}>{props.title}</Button>
```
板谷さんが書いてくれている色の設定がマージされたら、その色を使いたいですね。

2024-11-18 09:25 UTC, Harineko0 requested changes
LGTM です！
何点かコメントしましたので、ご確認お願いします。

2024-11-18 09:25 UTC, Harineko0 commented on app/components/primary-button.tsx
> +    title: string;
Button の中に入るテキストは title よりも label と呼ばれることが多いですね！
また、React では label で文字列を渡すより、children として ReactNode を渡すのが一般的です
```suggestion
    children: ReactNode
```
こうすれば、以下のようにコンポーネントを使用できます
```TypeScriot
<PrimaryButton>
  Test
</PrimaryButton>
```

2024-11-18 09:25 UTC, Harineko0 commented on app/components/primary-button.tsx
> +interface IButtonInfo {
コンポーネントの引数 (props) のインターフェースは、コンポーネント名 + Props と命名されるのが一般的ですねー
```suggestion
interface PrimaryButtonProps {
```
interface を使っているのは good です

2024-11-18 09:25 UTC, Harineko0 commented on app/components/primary-button.tsx
> +export function PrimaryButton(props: IButtonInfo){
Lint をかければ自動で修正できますが、TypeScript では arguments の丸括弧と statement の波括弧は間にスペースを入れますね

```suggestion
export function PrimaryButton(props: IButtonInfo) {
```

2024-11-18 09:25 UTC, Harineko0 commented on app/components/primary-button.tsx
> +        <Button variant="outline" onClick={props.onClick}>{props.title}</Button>
そもそも、variant でコンポーネントを分ける必要はあまりないですねｗ
勝又さんに強く言い返せなかった私が悪かったです。

ボタンをコンポーネントとして分割するのは、そのコンポーネントにドメイン知識寄りの役割がある場合か、見た目以外の機能 (onClick が非同期のため処理が終わるまで disabled にするときなど) がある場合に限るべきだと思います。

2024-11-18 09:25 UTC, Harineko0 commented on app/layout/header.tsx
> +                            <PrimaryButton title="Test2" onClick={()=>{alert("success")}}></PrimaryButton>
nits: こちらも、=> の両側にスペースを付けたほうがいいですねー
あとは、関数呼出しを一行で行う場合は波括弧は無くても動きます。また、タグの中に要素を入れない場合は閉じタグは書かなくても ok ですｂ

```suggestion
<PrimaryButton title="Test2" onClick={() => alert("success")} />
```

2024-12-08 12:28 UTC, kobayashi020 commented
![スクリーンショット 2024-12-08 212337](https://github.com/user-attachments/assets/b5f84c37-4fad-4880-94f3-8862d19deb99)
![スクリーンショット 2024-12-08 212405](https://github.com/user-attachments/assets/236ff7af-56e5-4d43-9c40-01e608dda1d0)
Submitボタンを押すと画像のように「success」と表示されるようにしました。

2025-01-04 23:18 UTC, wf9a5m75 commented
@iusok3386 さん、フォローアップしてコンフリクトを @kobayashi020 さんと修正してマージしてください

2025-01-25 23:48 UTC, merged