[DOJO-11] コンポーネントの作成 (ボタン)
Greek-Academy/alpha-dojo-v2 pull request #3
Opened 2024-11-14 13:12 UTC by iusok3386

#2 と被りそうですが。
こちらのブランチでは Add New Problem のようなヘッダーじゃないボタンを実装したつもりです。
ヘッダー用のボタンも一応作ってみたのですが、もし必要であれば追加でコミットします。

[app/component](https://github.com/Greek-Academy/alpha-dojo-v2/tree/dev/components/button/app/components) にページ内の大きめのコンポーネント (問題画面、コード画面、通知など) を配置して、
[app/ui](https://github.com/Greek-Academy/alpha-dojo-v2/tree/dev/components/button/app/ui) に小さいコンポーネント (ボタン、アイコンなど) を配置してみたのですが、どうでしょうか。

[Jira] TO DO: [DOJO-11](https://alpha-dojo.atlassian.net/browse/DOJO-11?atlOrigin=eyJpIjoiZDg3MTMyMGY1MjJmNGIzZjkzYzAzNGI2Mzk1MTU5ZDkiLCJwIjoiaiJ9) (ボタン)

2024-11-16 23:24 UTC, itakosu55 commented
Icon のコンポーネント化の件は修正しておきます

2024-11-16 23:26 UTC, itakosu55 commented
![image](https://github.com/user-attachments/assets/462400c8-3b5f-45f9-95e9-54373b6cfaa7)

2024-11-18 11:22 UTC, Harineko0 requested changes
LGTM です！

Figma がまだ固まっておらず混乱させて申し訳ないですが、`Add New Problem` のボタンは普通のボタンなので、 shadcn が自動生成した Button.tsx を直接変更していただいて問題ありませんｂ
むしろ、ヘッダーやウィンドウのタブに使われるボタンが特殊ですね

2024-11-18 11:22 UTC, Harineko0 commented on app/ui/Button/ActionButton.tsx
> +import { Button, ButtonProps } from "@/components/ui/button"
このファイルは components/ 配下に置きましょう！

2024-11-18 11:22 UTC, Harineko0 commented on app/ui/Button/ActionButton.tsx
> +                {...props}>
`asChild`, `size`, `variant` は props にまとめて良さそうですねー
className を合成するときは `clsx` を使った方がいいと思います、 shadcn が自動生成したものの中にあるはずです
それと、tailwind で値を直接指定するのはなるべく避けたほうがいいですねー

```suggestion
        <Button className={`gap-0 pl-4 pr-6 py-2 rounded-full ${className}`}
                {...props}>
```

2024-11-18 11:22 UTC, Harineko0 commented on app/ui/Button/ActionButton.tsx
> +            }
アイコンを追加するときは、アイコンのプロパティを Prop で渡すのではなく、アイコンコンポーネントそのものを渡した方がよいですね
例えば MaterialSymbols コンポーネントの Props を変更した際、このコンポーネントの Props も変更しなければならなくなります！ この辺りはオブジェクト指向の委譲と継承と同じ話ですね。

```suggestion
            // icon?: ReactNode
            {icon}
```

2024-11-18 11:22 UTC, Harineko0 commented on app/ui/Button/ActionButton.tsx
> +            }
こちらも、直接値を指定するのはやめた方がよいですねー
それと、ここの波括弧は不要ですね

```suggestion
            <span className="ml-2">
                {children}
            </span>
```

2024-11-18 11:22 UTC, Harineko0 commented on app/ui/Icons/MaterialSymbols.tsx
> +export const MaterialSymbols = ({
MaterialSymbols を直接 export するとアイコンを使用するコードが Material Symbols に依存してしまうので、それぞれのアイコンのみ export するようにしましょうか
ちなみに、react-icons ライブラリは Material Icons もサポートしてるので、そちらを使う方が良いように思います

2024-11-18 12:31 UTC, iusok3386 commented on app/ui/Button/ActionButton.tsx
> +                {...props}>
もし Figma の指定が Tailwind にない場合はどうすればいいですか？
近い値を採用すればいいですか？

2024-11-18 12:33 UTC, iusok3386 commented on app/ui/Icons/MaterialSymbols.tsx
> +export const MaterialSymbols = ({
あ、そうなんですね！
とりあえず React Icons の Material Symbols でやっておきます。

2024-11-18 14:58 UTC, Harineko0 commented on app/ui/Button/ActionButton.tsx
> +                {...props}>
ですね、そこまで厳密に Figma に合わせなくて ok です

2024-11-20 01:07 UTC, itakosu55 commented on app/ui/Button/ActionButton.tsx
> +import { Button, ButtonProps } from "@/components/ui/button"
revert しました。
https://github.com/Greek-Academy/alpha-dojo-v2/pull/3/commits/41ed47d05a3f7a309e45c30425dd0ade38162962

2024-11-20 01:21 UTC, iusok3386 commented on app/ui/Icons/MaterialSymbols.tsx
> +export const MaterialSymbols = ({
Material Symbols は無いんですね
まあ、そんなに変わらないか

2024-11-20 04:24 UTC, iusok3386 commented on app/ui/Icons/MaterialSymbols.tsx
> +export const MaterialSymbols = ({
修正しましたが、少し問題が発生しました。
Material Symbols はフォントサイズごとにアイコンが作成されていたので問題に放っていませんでしたが、
React Icons は 24px の SVG を縮小表示しているので、100% 表示のディスプレイではアイコンがにじんで表示されることがあります。
![image](https://github.com/user-attachments/assets/4cb670d2-9ca9-4f33-bde4-f1ecdc41fd32)

2024-11-20 06:05 UTC, iusok3386 commented on app/ui/Button/ActionButton.tsx
> +            }
修正しました！
https://github.com/Greek-Academy/alpha-dojo-v2/pull/3/commits/98fc265f880736a434ee9f8b5e9b7e7249f8281b

2024-11-20 06:06 UTC, iusok3386 commented on app/ui/Button/ActionButton.tsx
> +            }
修正しました！
https://github.com/Greek-Academy/alpha-dojo-v2/pull/3/commits/98fc265f880736a434ee9f8b5e9b7e7249f8281b

2024-11-20 06:12 UTC, iusok3386 commented
最終的には React Icons 導入しただけになってしまいましたね (-_-;)

2024-11-20 08:51 UTC, Harineko0 commented on app/ui/Icons/MaterialSymbols.tsx
> +export const MaterialSymbols = ({
あー、そうなんですね・・・じゃあやっぱり Material Symbols で大丈夫です、出戻りしてすみません・・・

2024-11-20 09:02 UTC, Harineko0 reviewed
ありがとうございます！
細かい指摘が続いて申し訳ないんですが、少しコメント付けましたm(__)m
ご確認お願いします

2024-11-20 09:02 UTC, Harineko0 commented on app/components/Icons/MaterialIcons.tsx
> +};
細かい話で申し訳ないんですが、ディレクトリの命名は dojo v0 に合わせて kebab-case でお願いします m(__)m

2024-11-20 09:02 UTC, Harineko0 commented on app/components/Icons/MaterialIcons.tsx
> +export const MdIconAdd = (props: IconBaseProps) => {
nits: ここはシンプルに `MdIconAdd` -> `AddIcon` で良さそうです
```suggestion
export const AddIcon = (props: IconBaseProps) => {
```

2024-11-20 11:18 UTC, iusok3386 commented on app/components/Icons/MaterialIcons.tsx
> +};
kebab-case、なるほどですね

2024-11-20 11:19 UTC, iusok3386 commented on app/components/Icons/MaterialIcons.tsx
> +export const MdIconAdd = (props: IconBaseProps) => {
他のコンポーネントと被ったりは大丈夫そうですか？

2024-11-22 13:40 UTC, iusok3386 commented on app/components/Icons/MaterialIcons.tsx
> +};
修正しました
https://github.com/Greek-Academy/alpha-dojo-v2/pull/3/commits/3e65dc6169ad88684a6617514e80723ecaa76781

2024-11-22 13:40 UTC, iusok3386 commented on app/components/Icons/MaterialIcons.tsx
> +export const MdIconAdd = (props: IconBaseProps) => {
修正しました
https://github.com/Greek-Academy/alpha-dojo-v2/pull/3/commits/97f50201087c50483bc469e7f92a52453bb913a4

2024-11-22 13:42 UTC, iusok3386 commented on app/ui/Icons/MaterialSymbols.tsx
> +export const MaterialSymbols = ({
修正しました
https://github.com/Greek-Academy/alpha-dojo-v2/pull/3/commits/c0dd4e993f64c96939ca444c51cde68a6cc3cbb3
https://github.com/Greek-Academy/alpha-dojo-v2/pull/3/commits/afa4728f6539d9917ba64c39d47c2d7efa3837f3
https://github.com/Greek-Academy/alpha-dojo-v2/pull/3/commits/60cb5529a1a6f22d0cb1653b3b776b141a7d0b1c

2024-11-23 16:13 UTC, Harineko0 approved these changes
LGTM! ありがとうございますm(__)m

2024-11-23 23:23 UTC, merged